name = "<NAME>"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "<ACCOUNT_ID>"
workers_dev = true
route = ""
zone_id = ""

#kv_namespaces = [
#	 { binding = "<NAME>", id = "<ID>" }
#]

[build]
command = "yarn install && yarn run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
#bindings = [{name = "<NAME>", class_name = "<CLASSNAME>"}]
